### ISSUE TITLE
using with macports installed ruby

### ISSUE THREAD

**Issue by HarryGuerrilla** [dmexe/emacs-rails-reloaded#1]
I use ruby installed via macports in /opt/local/bin/ruby.  When I use emacs-rails-reloaded I get errors running the webserver etc becasue it can't find my gems and is using the standard installation of ruby on my mac instead.  Any ideas on how I can fix this?

**Comment by dmexe** [comment]
Hi, 
Sorry for long time.

try:
(defvar rails/ruby/command "/opt/local/bin/ruby")
(require 'rails-autoload)
